-- ============================================================
-- ClyvoVet — Schema mínimo (Sprint 3 Mobile)
-- Apenas as 3 tabelas que o app realmente usa.
-- Sem procedures/functions/triggers — isso é escopo de outra disciplina.
-- Isolamento de dados por usuário via uid_firebase (Firebase Auth).
-- ============================================================

-- Responsável (tutor do animal) — raiz do isolamento por usuário
CREATE TABLE T_CLYVO_RESPONSAVEL (
    id_responsavel      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid_firebase         VARCHAR2(128) NOT NULL,
    cpf_responsavel       VARCHAR2(20) NOT NULL,
    nm_responsavel        VARCHAR2(100) NOT NULL,
    nr_telefone_responsavel VARCHAR2(20) NOT NULL,
    -- mesmo CPF pode existir para USUÁRIOS diferentes (cada um só vê o seu),
    -- mas não pode duplicar CPF dentro do mesmo usuário
    CONSTRAINT uq_responsavel_cpf_usuario UNIQUE (uid_firebase, cpf_responsavel)
);

-- Animal — sempre vinculado a um responsável
CREATE TABLE T_CLYVO_ANIMAL (
    id_animal            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rg_animal             VARCHAR2(20),
    nr_microchip_animal    VARCHAR2(20),
    nm_animal              VARCHAR2(100) NOT NULL,
    dt_nascimento_animal    DATE,
    peso_animal            NUMBER(6,2),
    especie_animal          VARCHAR2(50) NOT NULL,
    raca_animal             VARCHAR2(50),
    id_responsavel          NUMBER NOT NULL,
    CONSTRAINT fk_animal_responsavel FOREIGN KEY (id_responsavel)
        REFERENCES T_CLYVO_RESPONSAVEL (id_responsavel)
        ON DELETE CASCADE
);

-- Consulta — sempre vinculada a um animal (e, por herança, ao responsável e ao usuário)
CREATE TABLE T_CLYVO_CONSULTA (
    id_consulta           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    historico_consulta      VARCHAR2(500) NOT NULL,
    st_consulta             VARCHAR2(20) NOT NULL,
    dt_consulta             DATE NOT NULL,
    hr_consulta             VARCHAR2(5) NOT NULL, -- formato 'HH:MM', texto simples
    id_animal               NUMBER NOT NULL,
    CONSTRAINT ck_status_consulta CHECK (st_consulta IN ('Agendado', 'Concluido', 'Atrasado')),
    CONSTRAINT fk_consulta_animal FOREIGN KEY (id_animal)
        REFERENCES T_CLYVO_ANIMAL (id_animal)
        ON DELETE CASCADE
);

-- ============================================================
-- Índices auxiliares (buscas mais comuns do app)
-- ============================================================
CREATE INDEX idx_responsavel_uid ON T_CLYVO_RESPONSAVEL (uid_firebase);
CREATE INDEX idx_animal_responsavel ON T_CLYVO_ANIMAL (id_responsavel);
CREATE INDEX idx_consulta_animal ON T_CLYVO_CONSULTA (id_animal);

-- ============================================================
-- Dados de exemplo
-- uid_firebase = 'dev-user-1' porque é o uid fixo que o backend usa
-- quando AUTH_MODE=open (ver src/middlewares/auth.ts). Isso permite
-- testar tudo agora, sem depender do Firebase ainda.
--
-- Quando o Firebase estiver plugado (AUTH_MODE=strict), troque estas
-- 2 linhas de uid_firebase pelo uid real do seu usuário de teste
-- (Console do Firebase > Authentication > coluna "UID"), ou os dados
-- de exemplo abaixo deixam de aparecer para qualquer usuário real.
-- ============================================================

INSERT INTO T_CLYVO_RESPONSAVEL (uid_firebase, cpf_responsavel, nm_responsavel, nr_telefone_responsavel)
VALUES ('dev-user-1', '45812579024', 'Jaci Oliveira', '11934567890');

INSERT INTO T_CLYVO_RESPONSAVEL (uid_firebase, cpf_responsavel, nm_responsavel, nr_telefone_responsavel)
VALUES ('dev-user-1', '54823687074', 'Felipe Santos', '11987456123');

INSERT INTO T_CLYVO_ANIMAL (rg_animal, nr_microchip_animal, nm_animal, dt_nascimento_animal, peso_animal, especie_animal, raca_animal, id_responsavel)
VALUES (NULL, '5482', 'Arthur', TO_DATE('2024-04-20', 'YYYY-MM-DD'), 60.5, 'Cachorro', 'Golden Retriever', 1);

INSERT INTO T_CLYVO_ANIMAL (rg_animal, nr_microchip_animal, nm_animal, dt_nascimento_animal, peso_animal, especie_animal, raca_animal, id_responsavel)
VALUES (NULL, NULL, 'Fofucho', TO_DATE('2020-08-10', 'YYYY-MM-DD'), 4.2, 'Gato', 'Laranja', 2);

INSERT INTO T_CLYVO_CONSULTA (historico_consulta, st_consulta, dt_consulta, hr_consulta, id_animal)
VALUES ('Consulta de rotina, vacinação em dia', 'Concluido', TO_DATE('2026-07-10', 'YYYY-MM-DD'), '14:30', 1);

INSERT INTO T_CLYVO_CONSULTA (historico_consulta, st_consulta, dt_consulta, hr_consulta, id_animal)
VALUES ('Retorno para avaliação de peso', 'Agendado', TO_DATE('2026-08-25', 'YYYY-MM-DD'), '09:00', 2);

COMMIT;