-- ============================================================
-- ClyvoVet — Schema completo (Sprint 3 Mobile)
-- 4 tabelas: Usuario, Responsavel, Animal, Consulta.
-- Sem procedures/functions/triggers — isso é escopo de outra disciplina.
-- Autenticação via JWT próprio (bcrypt + jsonwebtoken no backend).
--
-- Se rodar pela primeira vez, os DROP TABLE abaixo vão dar erro
-- "table or view does not exist" — é esperado, pode ignorar e
-- seguir rodando o resto do script normalmente.
-- ============================================================

-- ============================================================
-- DROP (ordem inversa de dependência: quem referencia primeiro,
-- quem é referenciado por último)
-- ============================================================

DROP TABLE T_CLYVO_CONSULTA;
DROP TABLE T_CLYVO_ANIMAL;
DROP TABLE T_CLYVO_RESPONSAVEL;
DROP TABLE T_CLYVO_USUARIO;

-- ============================================================
-- Usuário
-- Guarda quem pode logar no app (nome, e-mail e a senha já
-- criptografada — nunca a senha em texto puro). É criado quando
-- alguém se cadastra pela tela de Cadastro do app.
-- ============================================================
CREATE TABLE T_CLYVO_USUARIO (
    id_usuario     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_usuario     VARCHAR2(100) NOT NULL,
    email_usuario  VARCHAR2(150) NOT NULL,
    senha_hash     VARCHAR2(255) NOT NULL,
    dt_criacao     DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT uq_usuario_email UNIQUE (email_usuario)
);

-- ============================================================
-- Responsável
-- É o tutor/dono do animal (nome, CPF, telefone). Cada
-- responsável pertence a um usuário do app (coluna id_usuario_dono,
-- que guarda o id_usuario de quem cadastrou) — assim, cada
-- usuário só vê os responsáveis que ele mesmo criou.
-- ============================================================
CREATE TABLE T_CLYVO_RESPONSAVEL (
    id_responsavel           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario_dono          NUMBER NOT NULL,
    cpf_responsavel          VARCHAR2(20) NOT NULL,
    nm_responsavel           VARCHAR2(100) NOT NULL,
    nr_telefone_responsavel  VARCHAR2(20) NOT NULL,
    CONSTRAINT fk_responsavel_usuario FOREIGN KEY (id_usuario_dono)
        REFERENCES T_CLYVO_USUARIO (id_usuario)
        ON DELETE CASCADE,
    CONSTRAINT uq_responsavel_cpf_usuario UNIQUE (id_usuario_dono, cpf_responsavel)
);

-- ============================================================
-- Animal
-- É o paciente (nome, espécie, raça, peso, etc). Sempre pertence
-- a um responsável — se o responsável for removido, o animal
-- dele também é removido automaticamente (ON DELETE CASCADE).
-- ============================================================
CREATE TABLE T_CLYVO_ANIMAL (
    id_animal             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rg_animal             VARCHAR2(20),
    nr_microchip_animal   VARCHAR2(20),
    nm_animal             VARCHAR2(100) NOT NULL,
    dt_nascimento_animal  DATE,
    peso_animal           NUMBER(6,2),
    especie_animal        VARCHAR2(50) NOT NULL,
    raca_animal           VARCHAR2(50),
    id_responsavel        NUMBER NOT NULL,
    CONSTRAINT fk_animal_responsavel FOREIGN KEY (id_responsavel)
        REFERENCES T_CLYVO_RESPONSAVEL (id_responsavel)
        ON DELETE CASCADE
);

-- ============================================================
-- Consulta
-- É o registro de atendimento do animal (motivo, data, hora,
-- status). Sempre pertence a um animal — se o animal for
-- removido, as consultas dele também são (ON DELETE CASCADE).
-- Status só pode ser: Agendado, Concluido ou Atrasado.
-- ============================================================
CREATE TABLE T_CLYVO_CONSULTA (
    id_consulta          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    historico_consulta   VARCHAR2(500) NOT NULL,
    st_consulta          VARCHAR2(20) NOT NULL,
    dt_consulta          DATE NOT NULL,
    hr_consulta          VARCHAR2(5) NOT NULL,
    id_animal            NUMBER NOT NULL,
    CONSTRAINT ck_status_consulta CHECK (st_consulta IN ('Agendado', 'Concluido', 'Atrasado')),
    CONSTRAINT fk_consulta_animal FOREIGN KEY (id_animal)
        REFERENCES T_CLYVO_ANIMAL (id_animal)
        ON DELETE CASCADE
);

-- ============================================================
-- Índices (deixam as buscas mais comuns do app mais rápidas)
-- ============================================================
CREATE INDEX idx_usuario_email ON T_CLYVO_USUARIO (email_usuario);
CREATE INDEX idx_responsavel_usuario ON T_CLYVO_RESPONSAVEL (id_usuario_dono);
CREATE INDEX idx_animal_responsavel ON T_CLYVO_ANIMAL (id_responsavel);
CREATE INDEX idx_consulta_animal ON T_CLYVO_CONSULTA (id_animal);

-- ============================================================
-- Dados de exemplo
-- Cria um usuário de teste (dev@clyvovet.dev / senha: dev123456,
-- já com hash bcrypt correspondente) e os dados de exemplo
-- vinculados a ele. Se você já tem um usuário de teste criado via
-- POST /auth/cadastro, pode pular este INSERT de usuário e trocar
-- o id_usuario_dono abaixo pelo id_usuario real dele.
-- ============================================================

INSERT INTO T_CLYVO_USUARIO (nm_usuario, email_usuario, senha_hash)
VALUES ('Usuário de Teste', 'dev@clyvovet.dev', '$2b$10$k2sBI/87IT9DGaGOS3SMQOYxUC4xClFQFIJKwsdZW8LD4JwyDJrr.');

INSERT INTO T_CLYVO_RESPONSAVEL (id_usuario_dono, cpf_responsavel, nm_responsavel, nr_telefone_responsavel)
VALUES (1, '45812579024', 'Jaci Oliveira', '11934567890');

INSERT INTO T_CLYVO_RESPONSAVEL (id_usuario_dono, cpf_responsavel, nm_responsavel, nr_telefone_responsavel)
VALUES (1, '54823687074', 'Felipe Santos', '11987456123');

INSERT INTO T_CLYVO_ANIMAL (rg_animal, nr_microchip_animal, nm_animal, dt_nascimento_animal, peso_animal, especie_animal, raca_animal, id_responsavel)
VALUES (NULL, '5482', 'Arthur', TO_DATE('2024-04-20', 'YYYY-MM-DD'), 60.5, 'Cachorro', 'Golden Retriever', 1);

INSERT INTO T_CLYVO_ANIMAL (rg_animal, nr_microchip_animal, nm_animal, dt_nascimento_animal, peso_animal, especie_animal, raca_animal, id_responsavel)
VALUES (NULL, NULL, 'Fofucho', TO_DATE('2020-08-10', 'YYYY-MM-DD'), 4.2, 'Gato', 'Laranja', 2);

INSERT INTO T_CLYVO_CONSULTA (historico_consulta, st_consulta, dt_consulta, hr_consulta, id_animal)
VALUES ('Consulta de rotina, vacinação em dia', 'Concluido', TO_DATE('2026-07-10', 'YYYY-MM-DD'), '14:30', 1);

INSERT INTO T_CLYVO_CONSULTA (historico_consulta, st_consulta, dt_consulta, hr_consulta, id_animal)
VALUES ('Retorno para avaliação de peso', 'Agendado', TO_DATE('2026-08-25', 'YYYY-MM-DD'), '09:00', 2);

COMMIT;